#!/usr/bin/env python3
from __future__ import annotations
import copy
from math import pi, sqrt, ceil
import os
from pathlib import Path
import sys
from typing import Union

# Try to import pythonscad
PS_AVAILABLE = False
try:
    import pythonscad
    from pythonscad import *
    PS_AVAILABLE = True
except ImportError:
    pass

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../../"))

from b13d.api.core import ShapeAPI, Shape, run_api_test, Direction, Implementation
from b13d.api.utils import dimXY, file_ensure_extension, lineSplineXY
from b13d.conversion.stlascii2stlbin import stlascii2stlbin

# Try to import backup APIs
try:
    from b13d.api.mf import MFShapeAPI, MF_AVAILABLE
except ImportError:
    MFShapeAPI = None
    MF_AVAILABLE = False

try:
    from b13d.api.tm import TMShapeAPI, TM_AVAILABLE
except ImportError:
    TMShapeAPI = None
    TM_AVAILABLE = False

class PsShapeAPI(ShapeAPI):
    """
    PythonSCAD Pylele API implementation
    """

    # Prefer manifold3d as backup API, fall back to trimesh if manifold3d not available
    if MF_AVAILABLE and MFShapeAPI is not None:
        backup_api = MFShapeAPI(implementation=Implementation.MANIFOLD)
    elif TM_AVAILABLE and TMShapeAPI is not None:
        backup_api = TMShapeAPI(implementation=Implementation.TRIMESH)
    else:
        backup_api = None
    
    tmp_counter = 0
    
    def _gen_tmp_fname(self) -> str:
        """ Generate a temporary filename """
        tmp_fname = f"ps_tmp_{self.tmp_counter}.stl"
        self.tmp_counter += 1
        return tmp_fname
    
    def export(self, shape: Shape, path: Union[str, Path], fmt: str) -> None:
        """ Export any of all supported filetypes """
        assert fmt in [".stl", ".scad", ".csg"]
        if fmt == ".stl":
            self.export_stl(shape=shape, path=path)
        elif fmt == ".scad":
            self.export_scad(shape=shape, path=path)
        elif fmt == ".csg":
            self.export_csg(shape=shape, path=path)
        else:
            assert False

    def export_best(self, shape: Shape, path: Union[str, Path]) -> None:
        return self.export_scad(shape=shape, path=path)

    def export_stl(self, shape: Shape, path: Union[str, Path]) -> None:
        """ Export .stl mesh """
        # Try to use pythonscad's native export first
        try:
            shape.solid.export(str(path))
        except Exception:
            # Fallback to generating scad and using scad2stl
            basefname, _ = os.path.splitext(str(path))
            scad_file = self.export_scad(shape=shape, path=basefname)
            from b13d.conversion.scad2stl import scad2stl
            stl_file = scad2stl(scad_file, command='openscad', implicit=False)
            # Ensure STL is binary format
            stlascii2stlbin(stl_file)

    def export_csg(self, shape: Shape, path: Union[str, Path]) -> None:
        """ Export .csg mesh """
        basefname, _ = os.path.splitext(str(path))
        scad_file = self.export_scad(shape=shape, path=basefname)
        from b13d.conversion.scad2csg import scad2csg
        return scad2csg(scad_file)

    def export_scad(self, shape: Shape, path: Union[str, Path]) -> str:
        """ Export .scad description """
        # For pythonscad, we need to generate the OpenSCAD representation
        # Since pythonscad doesn't have a direct scad_export, we'll use repr or similar
        outdir, fname = os.path.split(str(path))
        fname = file_ensure_extension(fname, ".scad")
        
        # Try to get OpenSCAD representation
        try:
            # Some pythonscad objects might have a way to get SCAD code
            if hasattr(shape.solid, 'to_scad'):
                scad_content = shape.solid.to_scad()
            elif hasattr(shape.solid, '__str__'):
                scad_content = str(shape.solid)
            else:
                # Fallback: create a simple scad file that calls the python script
                # This is not ideal but should work for basic shapes
                scad_content = f"// Generated by pythonscad backend\n"
                scad_content += f"// Shape representation may not be accurate\n"
                
            out_path = os.path.join(outdir, fname)
            with open(out_path, 'w') as f:
                f.write(scad_content)
                
            out_path_full = os.path.join(outdir, fname)
            assert os.path.isfile(out_path_full), f"ERROR: file {out_path_full} does not exist!"
            return out_path_full
        except Exception as e:
            # Last resort: create a placeholder file
            out_path = os.path.join(outdir, fname)
            with open(out_path, 'w') as f:
                f.write("// Error generating SCAD from pythonscad object\n")
            raise RuntimeError(f"Failed to export SCAD: {e}")

    def sphere(self, r: float) -> Shape:
        return PsBall(r, self)

    def box(self, l: float, wth: float, ht: float, center: bool = True) -> Shape:
        retval = PsBox(l, wth, ht, self, center=center)
        return retval

    def cone_x(self, h: float, r1: float, r2: float) -> Shape:
        return PsCone(h, r1, r2, direction="X", api=self).mv(h / 2, 0, 0)

    def cone_y(self, h: float, r1: float, r2: float) -> Shape:
        return PsCone(h, r1, r2, direction="Y", api=self).mv(0, h / 2, 0)

    def cone_z(self, h: float, r1: float, r2: float) -> Shape:
        return PsCone(h, r1, r2, direction="Z", api=self).mv(0, 0, h / 2)

    def regpoly_extrusion_x(self, l: float, rad: float, sides: int) -> Shape:
        return PsCone(l, r1=rad, r2=rad, sides=sides, direction="X", api=self)

    def regpoly_extrusion_y(self, l: float, rad: float, sides: int) -> Shape:
        return PsCone(l, r1=rad, r2=rad, sides=sides, direction="Y", api=self)

    def regpoly_extrusion_z(self, l: float, rad: float, sides: int) -> Shape:
        return PsCone(l, r1=rad, r2=rad, sides=sides, direction="Z", api=self)

    def cylinder_x(self, l: float, rad: float) -> Shape:
        return PsCone(l, r1=rad, r2=rad, direction="X", api=self)

    def cylinder_y(self, l: float, rad: float) -> Shape:
        return PsCone(l, r1=rad, r2=rad, direction="Y", api=self)

    def cylinder_z(self, l: float, rad: float) -> Shape:
        return PsCone(l, r1=rad, r2=rad, direction="Z", api=self)

    def cylinder_rounded_z(self, l: float, rad: float, domeRatio: float = 1) -> Shape:
        return PsRndRodZ(l, rad, domeRatio, api=self)

    def polygon_extrusion(self, path: list[tuple[float, float]], ht: float) -> Shape:
        return PsPolyExtrusionZ(path, ht, self)

    def spline_extrusion(
        self,
        start: tuple[float, float],
        path: list[tuple[float, float] | list[tuple[float, float, float, float]]],
        ht: float,
    ) -> Shape:
        if ht < 0:
            return PSLineSplineExtrusionZ(start, path, abs(ht), self).mv(
                0, 0, -abs(ht)
            )
        else:
            return PSLineSplineExtrusionZ(start, path, ht, self)

    def spline_revolve(
        self,
        start: tuple[float, float],
        path: list[tuple[float, float] | list[tuple[float, float, float, float]]],
        deg: float,
    ) -> Shape:
        return PSLineSplineRevolveX(start, path, deg, self)

    def regpoly_sweep(
        self, rad: float, path: list[tuple[float, float, float]]
    ) -> Shape:
        return PCirclePolySweep(rad, path, self)

    def text(self, txt: str, fontSize: float, tck: float, font: str) -> Shape:
        return PSTextZ(txt, fontSize, tck, font, self)

    def polyhedron(
        self,
        points: list[tuple[float, float, float]],
        faces: list[list[int]],
        convexity: int = 1,
    ) -> Shape:
        return PPolyhedron(points, faces, convexity, api=self)

    def genImport(self, infile: str, extrude: float = None) -> Shape:
        return PImport(infile, extrude=extrude, api=self)

    def rectangle(self, size, center=False) -> Shape:
        size = size if isinstance(size, (list, tuple)) else (size, size)
        w, h = size[0], size[1]
        sq = square(w, h)
        if center:
            sq = sq.translate((-w / 2, -h / 2))
        return PShape(self, solid=sq)

    def circle(self, r=None, d=None) -> Shape:
        if r is None and d is not None:
            r = d / 2.0
        # Use pythonscad's circle
        segments = self.fidelity.smoothing_segments() * 8
        c = circle(r=r, _fn=segments)
        # pythonscad's circle already centers by default
        return PShape(self, solid=c)

    def polygon(self, points, paths=None, convexity=1) -> Shape:
        return PShape(self, solid=polygon(points=points, paths=paths, convexity=convexity))

    def genImport(self, infile: str, extrude: float = None) -> Shape:
        return PImport(infile, extrude=extrude, api=self)

    def sphere_quadrant(self, rad: float, pickTop: bool, pickFront: bool):
        maxDim = Shape.MAX_DIM
        ball = self.sphere(rad)
        topCut = self.box(maxDim, maxDim, maxDim).mv(
            0, 0, -maxDim / 2 if pickTop else maxDim / 2
        )
        frontCut = self.box(maxDim, maxDim, maxDim).mv(
            maxDim / 2 if pickFront else -maxDim / 2, 0, 0
        )
        return ball.cut(topCut).cut(frontCut)

    def cylinder_half(self, rad: float, pickFront: bool, tck: float):
        maxDim = Shape.MAX_DIM
        rod = self.cylinder_z(tck, rad)
        cutter = self.box(maxDim, maxDim, maxDim).mv(
            maxDim / 2 if pickFront else -maxDim / 2, 0, 0
        )
        return rod.cut(cutter)


class PShape(Shape):
    """
    PythonSCAD Pylele Shape implementation for test
    """

    backup_solid = None  # use backup API to track solid properties for query ie bbox

    def __init__(
        self,
        api: PsShapeAPI,
        solid=None,
        color: tuple[int, int, int] = None,
    ):
        self.api: ShapeAPI = api
        self.color = color

        if solid is not None:
            # main solid
            self.solid = solid

            # backup solid: convert to .stl and import
            if self.api.backup_api is not None:
                self.backup_solid = self.api.backup_api.genImport(
                    self.api.export_stl(self, self.api._gen_tmp_fname())
                )
            else:
                self.backup_solid = None

    def _check_backup_solid(self):
        if isinstance(self.backup_solid, Shape):
            return True
        print(f"# WARNING: backup_solid wrong type {type(self.backup_solid)}")
        return False

    def _scad_func_eval(self, func):
        """ Evaluate a function and return the result """
        
        if self.api.backup_api is None:
            raise NotImplementedError("Backup API (manifold3d) required for function evaluation")

        # generate a fake box embedding the numeric value        
        lbox = PShape(self.api, solid=cube(func, 1))   

        # import .stl od the sphere
        tmp_fname = self.api._gen_tmp_fname()
        # print(f"tmp_fname = {tmp_fname}")
        import_stl = self.api.backup_api.genImport(
                self.api.export_stl(lbox, tmp_fname)
            )
        # read box size that embeds the numeric value
        return 2*import_stl.back()
    
    def _check_numeric(self, num: float) -> bool:
        """ Check if a number is numeric """
        if isinstance(num, (float, int)):
            return num
        else:
            print(f"# WARNING: {num} is not numeric")
            try:
                return self._scad_func_eval(num)
            except:
                assert f"# WARNING: {num} is not numeric"

    def cut(self, cutter: Shape) -> Shape:
        if cutter is None:
            return self
        self.solid = self.solid.difference(cutter.solid)
        if self._check_backup_solid() and cutter._check_backup_solid():
            self.backup_solid = self.backup_solid.cut(cutter.backup_solid)
        return self

    def dup(self) -> Shape:
        dup = copy.copy(self)
        if self._check_backup_solid():
            dup.backup_solid = self.backup_solid.dup()
        return dup

    def join(self, joiner: Shape) -> Shape:
        if joiner is None:
            return self
        self.solid = self.solid.union(joiner.solid)
        if self._check_backup_solid() and joiner._check_backup_solid():
            self.backup_solid = self.backup_solid.join(joiner.backup_solid)
        return self

    def intersection(self, intersector: Shape) -> Shape:
        if intersector is None:
            return self
        self.solid = self.solid.intersection(intersector.solid)
        if self._check_backup_solid() and intersector._check_backup_solid():
            self.backup_solid = self.backup_solid.intersection(intersector.backup_solid)
        return self

    def _smoothing_segments(self, dim: float) -> int:
        return ceil(abs(dim) ** 0.5 * self.api.fidelity.smoothing_segments())

    def mirror(self, normal=(0, 1, 0)) -> Shape:
        cmirror = self.solid.mirror(list(normal))
        dup = copy.copy(self)
        dup.solid = cmirror
        
        if self._check_backup_solid():
            dup.backup_solid = self.backup_solid.mirror(normal=normal)
        return dup

    def mv(self, x: float, y: float, z: float) -> Shape:
        self.solid = self.solid.translate([x, y, z])
        if self._check_backup_solid():
            try:      
                xi = self._check_numeric(x)
                yi = self._check_numeric(y)
                zi = self._check_numeric(z)                
                self.backup_solid = self.backup_solid.mv(xi, yi, zi)
            except Exception:
                pass
        return self

    def rotate_x(self, ang: float) -> Shape:
        self.solid = self.solid.rotx(ang)
        if self._check_backup_solid():
            self.backup_solid = self.backup_solid.rotate_x(ang)
        return self

    def rotate_y(self, ang: float) -> Shape:
        self.solid = self.solid.roty(ang)
        if self._check_backup_solid():
            self.backup_solid = self.backup_solid.rotate_y(ang)
        return self

    def rotate_z(self, ang: float) -> Shape:
        self.solid = self.solid.rotz(ang)
        if self._check_backup_solid():
            self.backup_solid = self.backup_solid.rotate_z(ang)
        return self
    
    def rotate(self, ang: float | tuple[float,float,float], direction: Direction = Direction.Z) -> Shape:
        if isinstance(ang, float) or isinstance(ang, int):
            return Shape.rotate(self, ang, direction)
        self.solid = self.solid.rotate(ang)
        if self._check_backup_solid():
            self.backup_solid = self.backup_solid.rotate(ang)
        return self

    def scale(self, x: float, y: float, z: float) -> Shape:
        self.solid = self.solid.scale([x, y, z])
        if self._check_backup_solid():
            self.backup_solid = self.backup_solid.scale(x, y, z)
        return self

    def hull(self) -> Shape:
        # Use backup API for hull operation
        if self._check_backup_solid():
            self.solid = self.backup_solid.hull()
            self.backup_solid = self.backup_solid.hull()
        return self

    def set_color(self, rgb: tuple[int, int, int] | Enum = None) -> Shape:
        if not rgb is None:
            self.color = rgb
        if not self.color is None:
            c = self.color.value if hasattr(self.color, 'value') else self.color
            c = [v/255.0 for v in c]
            self.solid = self.solid.color(c)
        return self

    def bbox(self) -> tuple[float, float, float]:
        if self._check_backup_solid():
            return self.backup_solid.bbox()
        else:
            return (0,0,0,0,0,0)

    def linear_extrude(self, height=None, center=False, twist=0, scale=1.0, slices=None) -> Shape:
        if self.solid is None:
            raise NotImplementedError("linear_extrude requires a solid")
        h = height if height is not None else 1.0
        self.solid = self.solid.linear_extrude(h)
        if center:
            self.solid = self.solid.translate([0, 0, -h / 2])
        if self._check_backup_solid():
            self.backup_solid = self.backup_solid.linear_extrude(height=height, center=center)
        return self

    def rotate_extrude(self, angle=360, convexity=1) -> Shape:
        if self.solid is None:
            raise NotImplementedError("rotate_extrude requires a solid")
        self.solid = self.solid.rotate_extrude(angle)
        if self._check_backup_solid():
            self.backup_solid = self.backup_solid.rotate_extrude(angle=angle)
        return self

    def offset(self, r=None, chamfer=False) -> Shape:
        if self.solid is None:
            raise NotImplementedError("offset requires a solid")
        delta = r if r is not None else 0.0
        self.solid = self.solid.offset(delta)
        if chamfer:
            self.solid = self.solid.offset_chamfer(delta)
        if self._check_backup_solid():
            self.backup_solid = self.backup_solid.offset(r=r, chamfer=chamfer)
        return self

    def projection(self, cut=False) -> Shape:
        if self.solid is None:
            raise NotImplementedError("projection requires a solid")
        self.solid = self.solid.projection(cut=cut)
        if self._check_backup_solid():
            self.backup_solid = self.backup_solid.projection(cut=cut)
        return self

    def minkowski(self, other: Shape = None) -> Shape:
        if other is None:
            return self
        # pythonscad doesn't seem to have minkowski, fallback to hull via backup
        if self._check_backup_solid():
            self.solid = self.backup_solid.minkowski(other.backup_solid)
        return self

    class PsBall(PShape):
        def __init__(self, rad: float, api: PsShapeAPI):
            super().__init__(api)
            self.rad = rad
            self.solid = sphere(rad, _fn=self._smoothing_segments(2 * pi * rad))
            if api.backup_api is not None:
                self.backup_solid = api.backup_api.sphere(rad)
            else:
                self.backup_solid = None

    class PsBox(PShape):
        def __init__(self, ln: float, wth: float, ht: float, api: PsShapeAPI, center: bool = True):
            """
            Create a box with given dimensions
            :param ln: length of the box
            :param wth: width of the box
            :param ht: height of the box
            :param api: API to use for the box
            :param center: if True, the box is centered at (0,0,0)
            """
            super().__init__(api)
            self.ln = ln
            self.wth = wth
            self.ht = ht
            # pythonscad's cube centers by default when center=True
            self.solid = cube(ln, wth, ht, center=center)
            if api.backup_api is not None:
                self.backup_solid = api.backup_api.box(ln, wth, ht, center=center)
            else:
                self.backup_solid = None

    class PsCone(PShape):
        def __init__(
            self, ln: float, r1: float, r2: float, direction: str, api: PsShapeAPI
        ):
            super().__init__(api)
            self.ln = ln
            self.r1 = r1
            self.r2 = r2

            if self.r2 is None:
                self.r2 = self.r1
                
            # Calculate segments for smoothness
            segs = self._smoothing_segments(2 * pi * max(self.r1, self.r2))
            
            # Create cylinder/cone
            self.solid = cylinder(h=ln, r1=self.r1, r2=self.r2, _fn=segs)
            
            # Center the cylinder
            self.solid = self.solid.translate([0, 0, -ln / 2])
            
            # Rotate based on direction
            if direction == "X":
                self.solid = self.solid.rotx(90)
            elif direction == "Y":
                self.solid = self.solid.roty(90)
            # Z direction needs no rotation

            if api.backup_api is not None:
                cone = api.backup_api.cone_x(ln, r1, r2) if direction == "X" else \
                       api.backup_api.cone_y(ln, r1, r2) if direction == "Y" else \
                       api.backup_api.cone_z(ln, r1, r2)
                self.backup_solid = cone.mv(-ln/2, 0, 0) if direction == "X" else \
                                  cone.mv(0, -ln/2, 0) if direction == "Y" else \
                                  cone.mv(0, 0, -ln/2)
            else:
                self.backup_solid = None

    class PsPolyExtrusionZ(PShape):
        def __init__(self, path: list[tuple[float, float]], ht: float, api: PsShapeAPI):
            super().__init__(api)
            self.path = path
            self.ht = ht
            # Create polygon and extrude
            poly = polygon(path)
            self.solid = poly.linear_extrude(ht)
            if api.backup_api is not None:
                self.backup_solid = api.backup_api.polygon_extrusion(path, ht)
            else:
                self.backup_solid = None

    class PSLineSplineExtrusionZ(PShape):
        def __init__(
            self,
            start: tuple[float, float],
            path: list[tuple[float, float] | list[tuple[float, float, float, float]]],
            ht: float,
            api: PsShapeAPI,
        ):
            super().__init__(api)
            self.path = path
            self.ht = ht
            if ht < 0:
                poly = polygon(lineSplineXY(start, path, abs(ht)))
                self.solid = poly.linear_extrude(ht).translate([0, 0, -abs(ht)])
            else:
                poly = polygon(lineSplineXY(start, path, ht))
                self.solid = poly.linear_extrude(ht)
            if api.backup_api is not None:
                self.backup_solid = api.backup_api.spline_extrusion(start, path, ht)
            else:
                self.backup_solid = None

    class PSLineSplineRevolveX(PShape):
        def __init__(
            self,
            start: tuple[float, float],
            path: list[tuple[float, float] | list[tuple[float, float, float, float]]],
            deg: float,
            api: PsShapeAPI,
        ):
            super().__init__(api)
            self.path = path
            self.deg = deg
            # Create profile and revolve
            poly = polygon(lineSplineXY(start, path))
            self.solid = poly.rotate_extrude(deg)
            if api.backup_api is not None:
                self.backup_solid = api.backup_api.spline_revolve(start, path, deg)
            else:
                self.backup_solid = None

    class PCirclePolySweep(PShape):
        def __init__(
            self,
            rad: float,
            path: list[tuple[float, float, float]],
            api: PsShapeAPI = PsShapeAPI,
        ):
            super().__init__(api)
            self.path = path
            self.rad = rad
            # Create circle and sweep along path
            circle_poly = circle(rad, _fn=self._smoothing_segments(2 * pi * rad))
            self.solid = circle_poly.path_extrude(path)
            if api.backup_api is not None:
                self.backup_solid = api.backup_api.regpoly_sweep(rad, path)
            else:
                self.backup_solid = None

    class PSTextZ(PShape):
        def __init__(
            self,
            txt: str,
            fontSize: float,
            tck: float,
            font: str,
            api: PsShapeAPI,
        ):
            super().__init__(api)
            self.txt = txt
            self.fontSize = fontSize
            self.tck = tck
            self.font = font

            # Create text and extrude
            text_shape = text(txt, size=fontSize)
            if font:
                # Try to set font if supported
                try:
                    text_shape = text_shape.font(font)
                except:
                    pass  # Font not supported, continue without it
            self.solid = text_shape.linear_extrude(tck)
            
            if api.backup_api is not None:
                self.backup_solid = api.backup_api.text(txt, fontSize, tck, font)
            else:
                self.backup_solid = None

    class PImport(PShape):
        def __init__(
            self,
            infile: str,
            extrude: float = None,
            api: PsShapeAPI = PsShapeAPI,
        ):
            super().__init__(api)
            assert os.path.isfile(infile) or os.path.isdir(
                infile
            ), f"ERROR: file/directory {infile} does not exist!"
            self.infile = infile

            _, fext = os.path.splitext(infile)

            # Import using pythonscad's osimport
            imported = osimport(infile)
            
            if extrude is not None:
                self.solid = imported.linear_extrude(extrude)
            else:
                self.solid = imported
                
            if api.backup_api is not None:
                self.backup_solid = api.backup_api.genImport(infile, extrude=extrude)
            else:
                self.backup_solid = None

if __name__ == "__main__":
    run_api_test("pythonscad")