name: TestUbuntuPyVista

on: [push]

jobs:
  build:
    strategy:
      max-parallel: 2
      continue-on-error: true
      fail-fast: false
      matrix:
        # https://github.com/actions/setup-python/issues/853
        python-version: ["3.12"]
        os: [ubuntu-latest] #, ubuntu-24.04, ubuntu-22.04] # latest and LTS
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    # python packages included in install_dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_pyvista.txt
    - name: install dependencies
      run: |
        chmod +x ./install_dependencies.sh
        ./install_dependencies.sh
    - name: pip configuration report
      run: |
        mkdir test
        pip list > ./test/pip_list.txt
    - name: Generate timestamp
      id: timestamp
      run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV
    - name: test_b13d
      run: |
        # export OMP_NUM_THREADS=1
        # export OPENBLAS_NUM_THREADS=1
        # export MKL_NUM_THREADS=1
        # export NUMEXPR_NUM_THREADS=1
        pytest -n 2./src/b13d/test.py
    - name: test_b1scad
      run: |
        pytest -n 2 ./src/b1scad/test.py
    - name: test_pylele
      run: |
        pytest -n 2 ./src/pylele/test.py
    - name: upload test output
      uses: actions/upload-artifact@v4
      with:
          # path depends on the tag and the module name
          name: pylele_test_out_pv_${{ matrix.python-version }}_${{ matrix.os }}_${{ env.timestamp }}
          path: test/**/*/*.py test/**/*/*.txt test/**/*/*.log test/**/*/*.out test/**/*/*.err test/**/*/*.stl test/**/*/*.glb test/**/*/*.scad test/**/*/*.step test/**/*/*.stp