name: TestUbuntu20p04

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04 # ubuntu-latest
    strategy:
      matrix:
        # https://github.com/actions/setup-python/issues/853
        python-version: ["3.8", "3.8.5", "3.8.10", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: pip configuration report
      run: |
        pip list
    - name: install dependencies
      run: | 
        sudo install_dependencies.sh
    - name: test
      run: |
        python ./pylele_test.py
