name: TestWindows

on: [push]

jobs:
  build:
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        # https://github.com/actions/setup-python/issues/853
        python-version: ["3.10"] # , "3.11", "3.12"]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    # python packages included in install_dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_min.txt
    - name: Install OpenSCAD
      run: choco install -y openscad
      shell: powershell
    #- name: install dependencies
    #  run: |
    #    chmod +x ./install_dependencies.sh
    #    sudo ./install_dependencies.sh
    - name: pip configuration report
      run: |
        mkdir test
        pip list > ./test/pip_list.txt
    - name: Generate timestamp
      id: timestamp
      run: echo "timestamp=$(Get-Date -Format 'yyyyMMdd_HHmmss')" >> $env:GITHUB_ENV
    - name: test_b13d
      run: |
        python3 ./src/b13d/test.py
       continue-on-error: true
    - name: test_b1scad
      run: |
        python3 ./src/b1scad/test.py
       continue-on-error: true
    - name: test_pylele
      run: |
        python3 ./src/pylele/test.py
       continue-on-error: true
    - name: upload test output
      uses: actions/upload-artifact@v4
      with:
          # path depends on the tag and the module name
          name: pylele_test_out_${{ matrix.python-version }}_${{ matrix.os }}_${{ env.timestamp }}
          path: test/**/**/**/* #find ./test/fretboard_assembly/cadquery/*
    #- name: test pylele.sh
    #  run: |
    #    source ./src/pylele.sh
    - name: test pylele2.sh
      run: |
        python ./src/pylele/pylele2/all_assembly.py -odoff -i cq
        if ($LASTEXITCODE -ne 0) {
          Write-Host "Script failed with exit code: $LASTEXITCODE"
          exit $LASTEXITCODE
        }
    - name: upload demo stl
      uses: actions/upload-artifact@v4
      with:
          # path depends on the tag and the module name
          name: pylele_stl_out_${{ matrix.python-version }}_${{ matrix.os }}_${{ env.timestamp }}
          path: build/LeleAllAssembly/LeleAllAssembly.stl
          # compression-level: 0 # no compression