name: TestUbuntu

on: [push]

jobs:
  build:
    runs-on:  ubuntu-latest # ubuntu-20.04
    strategy:
      matrix:
        # https://github.com/actions/setup-python/issues/853
        python-version: ["3.10"] #["3.8", "3.8.5", "3.8.10", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    # python packages included in install_dependencies    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: install dependencies
      run: | 
        chmod +x ./install_dependencies.sh
        sudo ./install_dependencies.sh
    - name: pip configuration report
      run: |
        mkdir test
        pip list > ./test/pip_list.txt
    - name: test pylele.sh
      run: |
        source pylele.sh
    - name: test pylele_assemble.py
      run: |
        python3 ./pylele1/pylele_assemble.py
    - name: test pylele2.sh
      run: |
        source pylele2.sh -odoff
    - name: upload demo stl
      uses: actions/upload-artifact@v4
      with:
          # path depends on the tag and the module name
          name: pylele_stl_out
          path: build/LeleAllAssembly/LeleAllAssembly.stl
          # compression-level: 0 # no compression
    - name: convert to glb
      run: |
        python3 ./api/stl2glb.py build/LeleAllAssembly/LeleAllAssembly.stl
    - name: upload glb
      uses: actions/upload-artifact@v4
      with:
          # path depends on the tag and the module name
          name: pylele_glb_out
          path: build/LeleAllAssembly/LeleAllAssembly.glb
          # compression-level: 0 # no compression
    - name: test
      run: |
        python ./pylele_test.py
    - name: upload test output
      uses: actions/upload-artifact@v4
      with:
          # path depends on the tag and the module name
          name: pylele_test_out
          path: test/**/**/**/* #find ./test/fretboard_assembly/cadquery/*
