name: TestUbuntu

on: [push]

jobs:
  build:
    runs-on:  ubuntu-latest # ubuntu-20.04
    strategy:
      matrix:
        # https://github.com/actions/setup-python/issues/853
        python-version: ["3.10"] #["3.8", "3.8.5", "3.8.10", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: pip configuration report
      run: |
        pip list
    - name: install dependencies
      run: | 
        chmod +x ./install_dependencies.sh
        sudo ./install_dependencies.sh
    - name: test
      run: |
        python ./pylele_test.py
    # for debugging, show all the files
    - name: show files
      run: |
        ls -R
        find ./test/ | grep stl
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
          # path depends on the tag and the module name
          name: pylele_test_out
          path: test/**/**/**/* #find ./test/fretboard_assembly/cadquery/*
    - name: test pylele.sh
      run: |
        source pylele.sh
    - name: test pylele_assemble.py
      run: |
        python3 ./pylele1/pylele_assemble.py
    - name: test pylele2.sh
      run: |
        source pylele2.sh
    - name: upload demo
      uses: actions/upload-artifact@v4
      with:
          # path depends on the tag and the module name
          name: pylele_demo_out
          path: build/LeleBottomAssembly*/*.stl